# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Java CI with Maven

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  setup:
    
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
        
  build:

    needs: setup
    
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    - name: Build with Maven
      run: mvn -B package --file app/pom.xml
      
  test:

    needs: build
    
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Test with Maven
      run: mvn -B test --file app/pom.xml