version: "3.3"

services:
  reverse_proxy:
    build: ./reverse_proxy
    image: juanca548/reverse_proxy
    networks:
      - front-tier
    secrets:
      - revprox_cert
      - revprox_key
    ports:
      - "80:80"
      - "443:443"
      
  database:
    build: 
       context: ./database
    image: juanca548/database
    user: postgres
    environment:
      POSTGRES_USER: gordonuser
      POSTGRES_PASSWORD_FILE: /run/secrets/postgres_password
      POSTGRES_DB: atsea
    ports:
      - "5432:5432" 
    networks:
      - back-tier
    secrets:
      - postgres_password

  appserver:
    build:
       context: app
       dockerfile: Dockerfile
    image: juanca548/app
    user: gordon
    ports:
      - "8080:8080" 
      - "5005:5005"
    networks:
      - front-tier
      - back-tier
    secrets:
      - postgres_password

  payment_gateway:
    build:
      context: payment_gateway
    image: juanca548/payment_gateway
    networks:
      - payment
    secrets:
      - payment_token

networks:
  front-tier:
  back-tier:
  payment:
    driver: overlay
    attachable: true

secrets:
  postgres_password:
    file: ./devsecrets/postgres_password
  payment_token:
    file: ./devsecrets/payment_token
  revprox_cert:
    file: ./certs/domain.crt
  revprox_key:
    file: ./certs/domain.key
